### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Mindo-Joseph**
#### What does this PR do?
creates a responsive clone of TNW page

#### Description of Task to be completed?
Using some specified guidelines by Microverse, recreate the next web  clone

#### How should this be manually tested?
Open index.html in your browser to test

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @Mindo-Joseph, @Angelesh1995. You have done well on this project:+1:. Now let's fix the following :fast_forward:**

1. The Live Link in your readme leads to another project.

2. You should use hyperlinks in your readme for neatness.

3. On medium screens, the TNW logo should appear on the leftmost part of the page and not within the top-three news section. Compare with the original and effect the change accordingly.

4. Your TNW logo does not show on small screens at all.

5. The margin between the **Latest Funding** section and the section below it seems to be too much.

6. In the section below, both the top and bottom containers should have equal widths at all screen sizes. Yours break within the medium screen size.
image

7. On medium screens, the **Latest Deals** section should be aligned 3 per row.

8. You haven't implemented mobile first approach in your styling. There shouldn't be a media query for the mobile screen size since that should be your base style. Please ensure you use mobile-first approach.



9. Provide a more descriptive pull rrquest title.

10. Fix the horizontal scroll that appears on medium screen size.

_**Kindly make these changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Comment by lekegitrepo** [comment]
### Hi Team 👏 👏 
### You have done a good job, the page looks beautiful. However, you still need to make some adjustments on the page as mentioned by the previous reviewer.

**_1. Fix the gaps:
  screen size: 768px_**

**_Before the latest deals section_**

image

**_Below the latest funding round section_**

image


**_This are the images from the original page of the same sections:_**

image

image

_**2. Try to position these links in latest funding section like the original page**_

**_small screen_**

tnw

**_This is the original:_**

image

**_3. Add margins in between these contents like the original
small screen_**

image

**_This is the original:_**

image

**_Implement these required changes and submit for review_**

**_If you have any doubt or question contact me on slack._**

### Reviewed by: Temitayo Adeleke

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require changes

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review by Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback :+1:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work @Mindo-Joseph and @Angelesh1995 
You have done a fantastic job building this, however, some of the issues brought to your notice by my colleague persist still. Please consider looking into those more closely, as well as looking into my comments below.

There are a lot of issues with responsiveness. Please consider the images below:
* Original
screenshot
* Yours
screenshot

* Yours
screenshot

* Yours
screenshot

* Original
screenshot

* Yours
screenshot
* Original
screenshot

Please consider ALL sections very closely, on ALL screen sizes and make the appropriate changes. Your project has a lot of potential and I am certain it will look great once you are done! :medal_military: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Really fantastic work! @Mindo-Joseph and @Angelesh1995 :medal_military: 
Your UI is absolutely fabulous :ok_hand: It has one tiny flaw and as such, I have left a comment below towards helping you solve it. Please consider it and request what should be your final review. I wish you the very best and see you at the very top :100: 

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).


##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### You guys have done really well :clap: and for also implementing changes from previous reviews. Your project looks good now. I, therefore, approve of it. Congratulations :boom: :100:
### You can merge and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
